# Generated by Django 5.2.1 on 2026-09-28 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundPeriodLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ten_ky', models.CharField(max_length=50, unique=True, verbose_name='Tên kỳ khóa sổ')),
                ('tu_ngay', models.DateField(verbose_name='Từ ngày')),
                ('den_ngay', models.DateField(verbose_name='Đến ngày')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm khóa')),
                ('ghi_chu', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('locked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_period_locks', to=settings.AUTH_USER_MODEL, verbose_name='Người khóa sổ')),
            ],
            options={
                'verbose_name': 'Khóa sổ quỹ',
                'verbose_name_plural': 'Khóa sổ quỹ',
                'db_table': 'fund_period_locks',
                'ordering': ['-tu_ngay'],
            },
        ),
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ma_phieu', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Mã phiếu (PT/PC...)')),
                ('loai_gd', models.CharField(choices=[('THU', 'Khoản thu'), ('CHI', 'Khoản chi')], db_index=True, max_length=5, verbose_name='Loại giao dịch')),
                ('so_tien', models.BigIntegerField(verbose_name='Số tiền (VNĐ)')),
                ('so_du_sau', models.BigIntegerField(default=0, verbose_name='Số dư sau giao dịch')),
                ('nguoi_thuc_hien', models.CharField(max_length=150, verbose_name='Người thực hiện')),
                ('hinh_thuc', models.CharField(choices=[('TIEN_MAT', 'Tiền mặt'), ('CHUYEN_KHOAN', 'Chuyển khoản')], default='TIEN_MAT', max_length=15, verbose_name='Hình thức')),
                ('ngay_gd', models.DateTimeField(db_index=True, verbose_name='Thời gian giao dịch')),
                ('ghi_chu', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Thuộc kỳ đã khóa sổ')),
                ('hoa_don', models.FileField(blank=True, null=True, upload_to='funds/invoices/%Y/%m/', verbose_name='Hóa đơn đính kèm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo phiếu')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transactions', to='events.activityevent', verbose_name='Sự kiện liên quan')),
            ],
            options={
                'verbose_name': 'Giao dịch quỹ',
                'verbose_name_plural': 'Sổ quỹ',
                'db_table': 'fund_transactions',
                'ordering': ['ngay_gd', 'id'],
            },
        ),
    ]
