# Generated by Django 5.2.1 on 2026-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Khóa chống ghi trùng'),
        ),
    ]
