# Generated by Django 5.2.1 on 2026-10-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_fundtransaction_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtransaction',
            name='request_fingerprint',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, verbose_name='Vân tay nội dung yêu cầu (idempotency)'),
        ),
    ]
