# Generated by Django 5.2.1 on 2026-10-07 07:05
#
# Review R04: tạo hàng NEO khóa bi sổ (FundLedgerAnchor, pk=1).
# Trước đây mọi writer chỉ khóa "dòng cuối" của sổ — sổ RỖNG thì không có
# hàng nào để khóa, 2 giao dịch song song cùng đọc số dư 0 rồi cùng ghi →
# mất cập nhật chuỗi số dư. Hàng neo tồn tại vĩnh viễn = chốt khóa ổn định.
# An toàn legacy: chỉ CREATE TABLE + INSERT hàng neo nếu chưa có; KHÔNG đụng
# bất kỳ dòng FundTransaction nào (không xóa/sửa lịch sử).

from django.db import migrations, models


def ensure_anchor_row(apps, schema_editor):
    Anchor = apps.get_model("funds", "FundLedgerAnchor")
    if not Anchor.objects.filter(pk=1).exists():
        Anchor.objects.create(pk=1, ghi_chu="Hàng neo khóa bi sổ (data migration 0004)")


def remove_anchor_row(apps, schema_editor):
    Anchor = apps.get_model("funds", "FundLedgerAnchor")
    Anchor.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_fundtransaction_request_fingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundLedgerAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ghi_chu', models.CharField(blank=True, default='Hàng neo khóa bi sổ', max_length=200, verbose_name='Ghi chú kỹ thuật')),
            ],
            options={
                'verbose_name': 'Hàng neo khóa bi sổ quỹ',
                'verbose_name_plural': 'Hàng neo khóa bi sổ quỹ',
                'db_table': 'fund_ledger_anchor',
            },
        ),
        migrations.RunPython(ensure_anchor_row, remove_anchor_row),
    ]

