# Generated by Django 5.2.1 on 2026-09-28 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ma_hd', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Mã hoạt động')),
                ('ten_hoat_dong', models.CharField(max_length=200, verbose_name='Tên hoạt động')),
                ('mo_ta', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('loai_hd', models.CharField(choices=[('WORKSHOP', 'Workshop'), ('HACKATHON', 'Hackathon'), ('SINH_HOAT_DINH_KY', 'Sinh hoạt định kỳ'), ('TEAMBUILDING', 'Teambuilding')], max_length=20, verbose_name='Loại hoạt động')),
                ('thoi_gian_bat_dau', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('thoi_gian_ket_thuc', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('dia_diem', models.CharField(max_length=255, verbose_name='Địa điểm')),
                ('vi_do', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('kinh_do', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('ban_kinh_m', models.FloatField(default=50, verbose_name='Bán kính check-in (m)')),
                ('tong_kinh_phi_du_tru', models.BigIntegerField(default=0, verbose_name='Tổng kinh phí dự trù (VNĐ)')),
                ('so_luong_toi_da', models.IntegerField(default=100, verbose_name='Số lượng tham gia tối đa')),
                ('trang_thai', models.CharField(choices=[('PLANNING', 'Đang lên kế hoạch'), ('OPEN_REGISTRATION', 'Mở đăng ký'), ('IN_PROGRESS', 'Đang diễn ra'), ('COMPLETED', 'Đã kết thúc'), ('CANCELLED', 'Đã hủy')], db_index=True, default='PLANNING', max_length=20, verbose_name='Trạng thái')),
                ('poster', models.URLField(blank=True, default='', max_length=500, verbose_name='Poster sự kiện (URL)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Hoạt động sự kiện',
                'verbose_name_plural': 'Hoạt động sự kiện',
                'db_table': 'activity_events',
                'ordering': ['-thoi_gian_bat_dau'],
            },
        ),
        migrations.CreateModel(
            name='EventBudgetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ten_hang_muc', models.CharField(max_length=200, verbose_name='Hạng mục chi tiêu')),
                ('so_tien', models.BigIntegerField(verbose_name='Số tiền dự trù (VNĐ)')),
                ('ghi_chu', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_details', to='events.activityevent')),
            ],
            options={
                'verbose_name': 'Hạng mục dự trù kinh phí',
                'verbose_name_plural': 'Dự trù kinh phí',
                'db_table': 'event_budget_details',
                'ordering': ['event', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('kenh', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok'), ('EMAIL', 'Email'), ('WEBSITE', 'Website'), ('OTHER', 'Khác')], max_length=15, verbose_name='Kênh truyền thông')),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tiêu đề bài đăng')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Deadline đăng bài')),
                ('link_bai_viet', models.URLField(blank=True, default='', max_length=500, verbose_name='Link bài viết')),
                ('trang_thai', models.CharField(choices=[('PENDING', 'Chưa đăng'), ('PUBLISHED', 'Đã đăng')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='events.activityevent')),
                ('nguoi_phu_trach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='members.memberprofile', verbose_name='Người phụ trách')),
            ],
            options={
                'verbose_name': 'Kế hoạch truyền thông',
                'verbose_name_plural': 'Kế hoạch truyền thông',
                'db_table': 'event_communications',
                'ordering': ['event', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='EventTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ten_task', models.CharField(max_length=200, verbose_name='Tên công việc')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Đã hoàn thành')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
                ('depends_on', models.ManyToManyField(blank=True, related_name='blocks', to='events.eventtask')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.activityevent')),
                ('nguoi_phu_trach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='members.memberprofile', verbose_name='Người phụ trách')),
            ],
            options={
                'verbose_name': 'Công việc sự kiện',
                'verbose_name_plural': 'Công việc sự kiện (DAG)',
                'db_table': 'event_tasks',
                'ordering': ['event', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ma_ve', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Mã vé (QR)')),
                ('trang_thai', models.CharField(choices=[('REGISTERED', 'Đã đăng ký'), ('APPROVED', 'Đã duyệt'), ('CHECKED_IN', 'Đã check-in'), ('CANCELLED', 'Đã hủy')], default='REGISTERED', max_length=15, verbose_name='Trạng thái vé')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.activityevent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Đăng ký sự kiện',
                'verbose_name_plural': 'Đăng ký sự kiện',
                'db_table': 'event_registrations',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'member'), name='unique_registration_per_event')],
            },
        ),
    ]
