# Generated by Django 5.2.1 on 2026-09-28 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ho_ten', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('ngay_sinh', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gioi_tinh', models.CharField(blank=True, choices=[('NAM', 'Nam'), ('NU', 'Nữ'), ('KHAC', 'Khác')], default='', max_length=5, verbose_name='Giới tính')),
                ('lop', models.CharField(blank=True, default='', max_length=50, verbose_name='Lớp')),
                ('sdt', models.CharField(blank=True, default='', max_length=15, verbose_name='Số điện thoại')),
                ('avatar', models.URLField(blank=True, default='', max_length=500, verbose_name='Ảnh đại diện (URL)')),
                ('xp_points', models.IntegerField(db_index=True, default=0, verbose_name='Điểm XP')),
                ('current_level', models.IntegerField(default=1, verbose_name='Cấp độ hiện tại (1-10)')),
                ('streak_count', models.IntegerField(default=0, verbose_name='Chuỗi chuyên cần 🔥')),
                ('last_attendance_date', models.DateField(blank=True, null=True, verbose_name='Lần điểm danh gần nhất')),
                ('trang_thai_hd', models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngừng hoạt động'), ('LEAVE', 'Bảo lưu')], db_index=True, default='ACTIVE', max_length=10, verbose_name='Trạng thái hoạt động')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ thành viên',
                'verbose_name_plural': 'Hồ sơ thành viên',
                'db_table': 'member_profiles',
                'ordering': ['-xp_points', 'ho_ten'],
            },
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('nhiem_ky', models.CharField(default='2025-2026', max_length=20, verbose_name='Nhiệm kỳ')),
                ('chuc_vu', models.CharField(choices=[('CHU_NHIEM', 'Chủ nhiệm'), ('PHO_CHU_NHIEM', 'Phó chủ nhiệm'), ('TRUONG_BAN', 'Trưởng ban'), ('PHO_BAN', 'Phó ban')], max_length=20, verbose_name='Chức vụ')),
                ('ban_phu_trach', models.CharField(choices=[('HOC_THUAT', 'Ban Học thuật'), ('TRUYEN_THONG', 'Ban Truyền thông'), ('SU_KIEN', 'Ban Sự kiện'), ('TAI_CHINH', 'Ban Tài chính')], max_length=20, verbose_name='Ban phụ trách')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_positions', to='members.memberprofile', verbose_name='Thành viên')),
            ],
            options={
                'verbose_name': 'Ban Chủ Nhiệm',
                'verbose_name_plural': 'Ban Chủ Nhiệm',
                'db_table': 'board_members',
                'ordering': ['nhiem_ky', 'chuc_vu'],
                'constraints': [models.UniqueConstraint(fields=('member', 'nhiem_ky'), name='unique_member_per_nhiem_ky')],
            },
        ),
    ]
