# Generated by Django 5.2.1 on 2026-09-28 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ma_badge', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Mã huy hiệu')),
                ('ten_badge', models.CharField(max_length=100, verbose_name='Tên huy hiệu')),
                ('mo_ta', models.CharField(max_length=255, verbose_name='Mô tả điều kiện mở khóa')),
                ('icon', models.CharField(blank=True, default='🏅', max_length=20, verbose_name='Icon (emoji/tên icon)')),
            ],
            options={
                'verbose_name': 'Huy hiệu',
                'verbose_name_plural': 'Huy hiệu',
                'db_table': 'badges',
                'ordering': ['ma_badge'],
            },
        ),
        migrations.CreateModel(
            name='XpLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('amount', models.IntegerField(verbose_name='Số XP thay đổi')),
                ('reason', models.CharField(max_length=255, verbose_name='Lý do')),
                ('source', models.CharField(choices=[('ATTENDANCE', 'Điểm danh'), ('DOCUMENT_SHARE', 'Chia sẻ tài liệu'), ('TASK_COMPLETION', 'Hoàn thành task'), ('EVENT_ORGANIZER', 'Tổ chức sự kiện'), ('BONUS', 'Thưởng khác')], default='BONUS', max_length=20, verbose_name='Nguồn')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Khóa chống lặp')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_ledger', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Sổ XP',
                'verbose_name_plural': 'Sổ XP',
                'db_table': 'xp_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm nhận')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='gamification.badge')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Huy hiệu thành viên',
                'verbose_name_plural': 'Huy hiệu thành viên',
                'db_table': 'member_badges',
                'ordering': ['-awarded_at'],
                'constraints': [models.UniqueConstraint(fields=('member', 'badge'), name='unique_badge_per_member')],
            },
        ),
    ]
