# Generated by Django 5.2.1 on 2026-09-28 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề tài liệu')),
                ('nhom', models.CharField(choices=[('CHUYEN_MON', 'Chuyên môn'), ('NGHIEP_VU', 'Nghiệp vụ'), ('KY_NANG', 'Kỹ năng')], db_index=True, max_length=15, verbose_name='Nhóm tài liệu')),
                ('tags', models.CharField(blank=True, default='', max_length=255, verbose_name='Tags chủ đề')),
                ('mo_ta', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('file', models.FileField(max_length=500, upload_to='documents/%Y/%m/', verbose_name='Tệp tài liệu')),
                ('file_type', models.CharField(blank=True, default='', max_length=10, verbose_name='Loại tệp')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Kích thước (bytes)')),
                ('luot_tai', models.IntegerField(db_index=True, default=0, verbose_name='Lượt tải')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Người chia sẻ')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Kho tài liệu',
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
