# Generated by Django 5.2.1 on 2026-09-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pham_vi',
            field=models.CharField(choices=[('PUBLIC_MEMBER', 'Toàn bộ thành viên'), ('BCN_ONLY', 'Chỉ Ban chủ nhiệm')], db_index=True, default='PUBLIC_MEMBER', max_length=20, verbose_name='Phạm vi truy cập'),
        ),
    ]
