# Generated by Django 5.2.1 on 2026-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('trang_thai', models.CharField(choices=[('CO_MAT', 'Có mặt'), ('VANG', 'Vắng'), ('CO_PHEP', 'Có phép'), ('DI_MUON', 'Đi muộn')], db_index=True, default='VANG', max_length=10, verbose_name='Trạng thái')),
                ('khoang_cach_m', models.FloatField(blank=True, null=True, verbose_name='Khoảng cách tới tâm (m)')),
                ('vi_do', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ thiết bị')),
                ('kinh_do', models.FloatField(blank=True, null=True, verbose_name='Kinh độ thiết bị')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Giờ check-in thực tế')),
                ('device_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Device fingerprint (hash UA + screen + hw)')),
                ('is_suspicious', models.BooleanField(default=False, verbose_name='Cờ gian lận SUSPICIOUS_FRAUD')),
                ('xp_awarded', models.IntegerField(default=0, verbose_name='XP được thưởng')),
            ],
            options={
                'verbose_name': 'Bản ghi điểm danh',
                'verbose_name_plural': 'Bản ghi điểm danh',
                'db_table': 'attendance_records',
                'ordering': ['session', 'member__ho_ten'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ten_phien', models.CharField(max_length=200, verbose_name='Tên phiên điểm danh')),
                ('vi_do', models.FloatField(verbose_name='Vĩ độ tâm')),
                ('kinh_do', models.FloatField(verbose_name='Kinh độ tâm')),
                ('ban_kinh_m', models.FloatField(default=50, verbose_name='Bán kính cho phép (m)')),
                ('mo_phien_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm mở phiên')),
                ('dong_phien_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm đóng phiên')),
                ('hieu_luc_den', models.DateTimeField(blank=True, null=True, verbose_name='Hiệu lực check-in đến')),
                ('trang_thai', models.CharField(choices=[('OPEN', 'Đang mở'), ('CLOSED', 'Đã đóng')], db_index=True, default='OPEN', max_length=10, verbose_name='Trạng thái phiên')),
                ('nonce_secret', models.CharField(blank=True, default='', max_length=64, verbose_name='Secret sinh nonce')),
            ],
            options={
                'verbose_name': 'Phiên điểm danh',
                'verbose_name_plural': 'Phiên điểm danh',
                'db_table': 'attendance_sessions',
                'ordering': ['-mo_phien_at'],
            },
        ),
    ]
