/** tailwind.config.js — theme clone 1:1 từ bản thiết kế CLB IP (Material 3)
 *
 * NẰM TRONG REPO để ai clone về cũng build lại được css/landing.css.
 * Content gồm: trang member home + landing công khai + file thiết kế gốc.
 *
 * Build (chạy trong thư mục frontend/tailwind/):
 *   npx tailwindcss@3.4.17 -c tailwind.config.js -i input.css -o ../css/landing.css --minify
 *
 * ⚠️ Thêm trang HTML mới dùng landing.css phải đưa vào `content` rồi build lại,
 *    nếu không class của trang mới sẽ không sinh ra CSS.
 */
module.exports = {
  darkMode: "class",
  content: [
    "./../member/home.html",
    "./../landing.html",
    "./design_reference.html",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-variant": "#dae2fd",
        "outline-variant": "#c7c4d7",
        "error-container": "#ffdad6",
        primary: "#4648d4",
        "surface-container-lowest": "#ffffff",
        surface: "#faf8ff",
        "inverse-surface": "#283044",
        "secondary-fixed-dim": "#d0bcff",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-secondary-container": "#fffbff",
        "secondary-container": "#8455ef",
        "on-secondary-fixed": "#23005c",
        "surface-tint": "#494bd6",
        "surface-bright": "#faf8ff",
        error: "#ba1a1a",
        "tertiary-fixed": "#acedff",
        tertiary: "#006577",
        outline: "#767586",
        "on-surface": "#131b2e",
        "surface-container-low": "#f2f3ff",
        "tertiary-container": "#008096",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#464554",
        "on-tertiary-container": "#f9fdff",
        "inverse-on-surface": "#eef0ff",
        "on-primary": "#ffffff",
        "secondary-fixed": "#e9ddff",
        "on-background": "#131b2e",
        "on-secondary-fixed-variant": "#5516be",
        "primary-fixed-dim": "#c0c1ff",
        "on-secondary": "#ffffff",
        "inverse-primary": "#c0c1ff",
        "on-error": "#ffffff",
        "primary-container": "#6063ee",
        "surface-container-high": "#e2e7ff",
        "surface-container": "#eaedff",
        "surface-dim": "#d2d9f4",
        background: "#faf8ff",
        "surface-container-highest": "#dae2fd",
        secondary: "#6b38d4",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#e1e0ff",
        "on-primary-fixed": "#07006c",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-tertiary-fixed": "#001f26",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.5rem",
        "margin-sm": "1rem",
        "gutter-sm": "1rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        margin: "2rem",
        gutter: "1.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        "headline-sm": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};
