# Generated by Django 5.2.1 on 2026-09-28 14:42

import apps.authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.authentication.models.UserManager()),
            ],
        ),
    ]
