# Generated by Django 5.2.1 on 2026-09-28 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('question', models.CharField(max_length=255, verbose_name='Câu hỏi bình chọn')),
                ('options', models.JSONField(default=list, verbose_name='Các lựa chọn')),
                ('votes', models.JSONField(default=dict, verbose_name='Kết quả bình chọn')),
                ('voted_user_ids', models.JSONField(default=list, verbose_name='User đã vote')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Đã đóng bình chọn')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Bình chọn cộng đồng',
                'verbose_name_plural': 'Bình chọn cộng đồng',
                'db_table': 'community_polls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('noi_dung', models.TextField(verbose_name='Nội dung góp ý')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='Ẩn danh')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_sent', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi (ẩn với BCN)')),
            ],
            options={
                'verbose_name': 'Hòm thư góp ý',
                'verbose_name_plural': 'Hòm thư góp ý',
                'db_table': 'feedback_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(verbose_name='Nội dung (đã sanitize HTML)')),
                ('anh_dinh_kem', models.URLField(blank=True, default='', max_length=500, verbose_name='Ảnh đính kèm (URL)')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, verbose_name='Được ghim')),
                ('pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm ghim')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa (soft)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_created', to=settings.AUTH_USER_MODEL, verbose_name='Người đăng')),
            ],
            options={
                'verbose_name': 'Bài đăng',
                'verbose_name_plural': 'Bảng tin',
                'db_table': 'posts',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Tạo mới'), ('UPDATE', 'Chỉnh sửa'), ('DELETE', 'Xóa'), ('PIN', 'Ghim'), ('UNPIN', 'Bỏ ghim')], max_length=10, verbose_name='Hành động')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm')),
                ('chi_tiet', models.TextField(blank=True, default='', verbose_name='Chi tiết thay đổi')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='posts.post')),
            ],
            options={
                'verbose_name': 'Audit log bài đăng',
                'verbose_name_plural': 'Audit log bài đăng',
                'db_table': 'post_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
